package fields

const Fields = "fields"
const AccessToken = "access_token"
const Platform = "platform"
const Biography = "biography"
const Bio = "bio"
const FollowersCount = "followers_count"
const FollowsCount = "follows_count"
const Id = "id"
const IgId = "ig_id"
const MediaCount = "media_count"
const ProfilePictureUrl = "profile_picture_url"
const Username = "username"
const Website = "website"
const Name = "name"
const Participants = "participants"
const UpdatedTime = "updated_time"
const CreatedTime = "created_time"
const UnreadCount = "unread_count"
const Message = "message"
const Reactions = "reactions"
const Shares = "shares"
